"""add_agent_templates

Revision ID: b97fc213d26c
Revises: d4a9f51927d4
Create Date: 2025-10-23 20:26:44.143252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b97fc213d26c'
down_revision: Union[str, None] = 'd4a9f51927d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('greeting_message', sa.Text(), nullable=False),
    sa.Column('sample_questions', sa.JSON(), nullable=True),
    sa.Column('recommended_voice', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('use_count', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_premium', sa.Boolean(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_templates_id'), 'agent_templates', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_templates_id'), table_name='agent_templates')
    op.drop_table('agent_templates')
    # ### end Alembic commands ###
