"""add_bulk_campaigns

Revision ID: 7f82a86437f1
Revises: 03f0b31519ad
Create Date: 2025-10-19 18:16:15.325818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f82a86437f1'
down_revision: Union[str, None] = '03f0b31519ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaign_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('campaign_type', sa.Enum('VOICE', 'SMS', 'BOTH', name='campaigntype'), nullable=False),
    sa.Column('voice_message', sa.Text(), nullable=True),
    sa.Column('sms_message', sa.Text(), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('times_used', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaign_templates_id'), 'campaign_templates', ['id'], unique=False)
    op.create_table('bulk_campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('phone_number_id', sa.Integer(), nullable=False),
    sa.Column('ai_agent_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('campaign_type', sa.Enum('VOICE', 'SMS', 'BOTH', name='campaigntype'), nullable=False),
    sa.Column('voice_message', sa.Text(), nullable=True),
    sa.Column('voice_audio_url', sa.String(), nullable=True),
    sa.Column('max_call_duration', sa.Integer(), nullable=True),
    sa.Column('enable_voicemail_detection', sa.Boolean(), nullable=True),
    sa.Column('leave_voicemail', sa.Boolean(), nullable=True),
    sa.Column('voicemail_message', sa.Text(), nullable=True),
    sa.Column('sms_message', sa.Text(), nullable=True),
    sa.Column('enable_sms_personalization', sa.Boolean(), nullable=True),
    sa.Column('scheduled_start', sa.DateTime(), nullable=True),
    sa.Column('scheduled_end', sa.DateTime(), nullable=True),
    sa.Column('timezone', sa.String(), nullable=True),
    sa.Column('calls_per_minute', sa.Integer(), nullable=True),
    sa.Column('calls_per_hour', sa.Integer(), nullable=True),
    sa.Column('concurrent_calls', sa.Integer(), nullable=True),
    sa.Column('max_retry_attempts', sa.Integer(), nullable=True),
    sa.Column('retry_delay_minutes', sa.Integer(), nullable=True),
    sa.Column('retry_on_no_answer', sa.Boolean(), nullable=True),
    sa.Column('retry_on_busy', sa.Boolean(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'SCHEDULED', 'RUNNING', 'PAUSED', 'COMPLETED', 'FAILED', name='campaignstatus'), nullable=True),
    sa.Column('total_recipients', sa.Integer(), nullable=True),
    sa.Column('completed_count', sa.Integer(), nullable=True),
    sa.Column('failed_count', sa.Integer(), nullable=True),
    sa.Column('success_count', sa.Integer(), nullable=True),
    sa.Column('estimated_cost', sa.Float(), nullable=True),
    sa.Column('actual_cost', sa.Float(), nullable=True),
    sa.Column('require_confirmation', sa.Boolean(), nullable=True),
    sa.Column('record_calls', sa.Boolean(), nullable=True),
    sa.Column('transcribe_calls', sa.Boolean(), nullable=True),
    sa.Column('collect_dtmf', sa.Boolean(), nullable=True),
    sa.Column('dtmf_options', sa.JSON(), nullable=True),
    sa.Column('respect_dnc', sa.Boolean(), nullable=True),
    sa.Column('quiet_hours_start', sa.String(), nullable=True),
    sa.Column('quiet_hours_end', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ai_agent_id'], ['ai_agents.id'], ),
    sa.ForeignKeyConstraint(['phone_number_id'], ['phone_numbers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bulk_campaigns_id'), 'bulk_campaigns', ['id'], unique=False)
    op.create_table('campaign_recipients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('custom_data', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', 'SKIPPED', name='recipientstatus'), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.Column('last_attempt_at', sa.DateTime(), nullable=True),
    sa.Column('call_id', sa.Integer(), nullable=True),
    sa.Column('call_duration', sa.Integer(), nullable=True),
    sa.Column('call_status', sa.String(), nullable=True),
    sa.Column('voicemail_detected', sa.Boolean(), nullable=True),
    sa.Column('dtmf_response', sa.String(), nullable=True),
    sa.Column('message_id', sa.String(), nullable=True),
    sa.Column('message_status', sa.String(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ),
    sa.ForeignKeyConstraint(['campaign_id'], ['bulk_campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaign_recipients_id'), 'campaign_recipients', ['id'], unique=False)
    op.create_index(op.f('ix_campaign_recipients_phone_number'), 'campaign_recipients', ['phone_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_campaign_recipients_phone_number'), table_name='campaign_recipients')
    op.drop_index(op.f('ix_campaign_recipients_id'), table_name='campaign_recipients')
    op.drop_table('campaign_recipients')
    op.drop_index(op.f('ix_bulk_campaigns_id'), table_name='bulk_campaigns')
    op.drop_table('bulk_campaigns')
    op.drop_index(op.f('ix_campaign_templates_id'), table_name='campaign_templates')
    op.drop_table('campaign_templates')
    # ### end Alembic commands ###
