"""add_subscriptions_and_ivr

Revision ID: d4a9f51927d4
Revises: 3a9e37184420
Create Date: 2025-10-23 19:34:49.435713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4a9f51927d4'
down_revision: Union[str, None] = '3a9e37184420'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
