"""add_subscriptions_and_ivr

Revision ID: 3a9e37184420
Revises: 905754844f10
Create Date: 2025-10-23 19:23:20.448051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a9e37184420'
down_revision: Union[str, None] = '905754844f10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tier', sa.Enum('FREE', 'BASIC', 'PRO', 'ENTERPRISE', name='subscriptiontier'), nullable=True),
    sa.Column('monthly_price', sa.Float(), nullable=True),
    sa.Column('monthly_minutes_included', sa.Integer(), nullable=True),
    sa.Column('monthly_minutes_used', sa.Integer(), nullable=True),
    sa.Column('additional_minute_rate', sa.Float(), nullable=True),
    sa.Column('max_phone_numbers', sa.Integer(), nullable=True),
    sa.Column('max_campaigns_per_month', sa.Integer(), nullable=True),
    sa.Column('max_concurrent_calls', sa.Integer(), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(), nullable=True),
    sa.Column('billing_cycle_start', sa.DateTime(), nullable=True),
    sa.Column('billing_cycle_end', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('trial_ends_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('canceled_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_subscriptions_id'), 'subscriptions', ['id'], unique=False)
    op.create_table('usage_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('feature_type', sa.Enum('AI_AGENT', 'OUTBOUND_CALLS', 'INBOUND_CALLS', 'BULK_CAMPAIGNS', 'CALL_RECORDING', 'TRANSCRIPTION', 'IVR_SYSTEM', 'SMS', 'ANALYTICS', 'API_ACCESS', name='featuretype'), nullable=False),
    sa.Column('resource_id', sa.String(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('unit_cost', sa.Float(), nullable=False),
    sa.Column('total_cost', sa.Float(), nullable=False),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usage_logs_id'), 'usage_logs', ['id'], unique=False)
    op.create_table('user_features',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=False),
    sa.Column('feature_type', sa.Enum('AI_AGENT', 'OUTBOUND_CALLS', 'INBOUND_CALLS', 'BULK_CAMPAIGNS', 'CALL_RECORDING', 'TRANSCRIPTION', 'IVR_SYSTEM', 'SMS', 'ANALYTICS', 'API_ACCESS', name='featuretype'), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=True),
    sa.Column('monthly_limit', sa.Integer(), nullable=True),
    sa.Column('current_usage', sa.Integer(), nullable=True),
    sa.Column('monthly_cost', sa.Float(), nullable=True),
    sa.Column('per_use_cost', sa.Float(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('enabled_at', sa.DateTime(), nullable=True),
    sa.Column('disabled_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_features_id'), 'user_features', ['id'], unique=False)
    op.create_table('ivr_flows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('phone_number_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('entry_node_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('total_calls_handled', sa.Integer(), nullable=True),
    sa.Column('avg_call_duration', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['phone_number_id'], ['phone_numbers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ivr_flows_id'), 'ivr_flows', ['id'], unique=False)
    op.create_table('business_hours',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('timezone', sa.String(), nullable=True),
    sa.Column('schedule', sa.JSON(), nullable=False),
    sa.Column('holidays', sa.JSON(), nullable=True),
    sa.Column('open_hours_flow_id', sa.Integer(), nullable=True),
    sa.Column('closed_hours_flow_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['closed_hours_flow_id'], ['ivr_flows.id'], ),
    sa.ForeignKeyConstraint(['open_hours_flow_id'], ['ivr_flows.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_hours_id'), 'business_hours', ['id'], unique=False)
    op.create_table('ivr_call_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('call_id', sa.Integer(), nullable=False),
    sa.Column('flow_id', sa.Integer(), nullable=False),
    sa.Column('nodes_visited', sa.JSON(), nullable=False),
    sa.Column('inputs_collected', sa.JSON(), nullable=True),
    sa.Column('final_action', sa.String(), nullable=True),
    sa.Column('transferred_to', sa.String(), nullable=True),
    sa.Column('total_duration', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ),
    sa.ForeignKeyConstraint(['flow_id'], ['ivr_flows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ivr_call_logs_id'), 'ivr_call_logs', ['id'], unique=False)
    op.create_table('ivr_nodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flow_id', sa.Integer(), nullable=False),
    sa.Column('node_type', sa.Enum('GREETING', 'MENU', 'GATHER_INPUT', 'TRANSFER', 'VOICEMAIL', 'AI_AGENT', 'HANGUP', 'PLAY_AUDIO', 'TEXT_TO_SPEECH', 'BUSINESS_HOURS', 'CALLBACK', name='ivrnodetype'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('position_x', sa.Integer(), nullable=True),
    sa.Column('position_y', sa.Integer(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('timeout_seconds', sa.Integer(), nullable=True),
    sa.Column('timeout_node_id', sa.Integer(), nullable=True),
    sa.Column('error_node_id', sa.Integer(), nullable=True),
    sa.Column('times_visited', sa.Integer(), nullable=True),
    sa.Column('avg_time_spent', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['error_node_id'], ['ivr_nodes.id'], ),
    sa.ForeignKeyConstraint(['flow_id'], ['ivr_flows.id'], ),
    sa.ForeignKeyConstraint(['timeout_node_id'], ['ivr_nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ivr_nodes_id'), 'ivr_nodes', ['id'], unique=False)
    op.create_table('ivr_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('trigger', sa.String(), nullable=False),
    sa.Column('next_node_id', sa.Integer(), nullable=True),
    sa.Column('conditions', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['next_node_id'], ['ivr_nodes.id'], ),
    sa.ForeignKeyConstraint(['node_id'], ['ivr_nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ivr_actions_id'), 'ivr_actions', ['id'], unique=False)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_ivr_actions_id'), table_name='ivr_actions')
    op.drop_table('ivr_actions')
    op.drop_index(op.f('ix_ivr_nodes_id'), table_name='ivr_nodes')
    op.drop_table('ivr_nodes')
    op.drop_index(op.f('ix_ivr_call_logs_id'), table_name='ivr_call_logs')
    op.drop_table('ivr_call_logs')
    op.drop_index(op.f('ix_business_hours_id'), table_name='business_hours')
    op.drop_table('business_hours')
    op.drop_index(op.f('ix_ivr_flows_id'), table_name='ivr_flows')
    op.drop_table('ivr_flows')
    op.drop_index(op.f('ix_user_features_id'), table_name='user_features')
    op.drop_table('user_features')
    op.drop_index(op.f('ix_usage_logs_id'), table_name='usage_logs')
    op.drop_table('usage_logs')
    op.drop_index(op.f('ix_subscriptions_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    # ### end Alembic commands ###
