"""Add ClientMapping table

Revision ID: 03f0b31519ad
Revises: 6eeff7f7e2f6
Create Date: 2025-10-18 17:11:24.564511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03f0b31519ad'
down_revision: Union[str, None] = '6eeff7f7e2f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
