"""add_rootcall_portal_models

Revision ID: 40508a9fb685
Revises: b97fc213d26c
Create Date: 2025-10-26 23:08:36.976638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40508a9fb685'
down_revision: Union[str, None] = 'b97fc213d26c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rootcall_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_number_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('client_name', sa.String(), nullable=False),
    sa.Column('client_cell', sa.String(), nullable=False),
    sa.Column('retell_agent_id', sa.String(), nullable=False),
    sa.Column('retell_did', sa.String(), nullable=False),
    sa.Column('trusted_contacts', sa.JSON(), nullable=True),
    sa.Column('caregiver_cell', sa.String(), nullable=True),
    sa.Column('sms_alerts_enabled', sa.Boolean(), nullable=True),
    sa.Column('alert_on_spam', sa.Boolean(), nullable=True),
    sa.Column('alert_on_unknown', sa.Boolean(), nullable=True),
    sa.Column('auto_block_spam', sa.Boolean(), nullable=True),
    sa.Column('require_caller_name', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['phone_number_id'], ['phone_numbers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_number_id')
    )
    op.create_index(op.f('ix_rootcall_configs_id'), 'rootcall_configs', ['id'], unique=False)
    op.create_table('trusted_contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rootcall_config_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('relationship_type', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('total_calls', sa.Integer(), nullable=True),
    sa.Column('last_call_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['rootcall_config_id'], ['rootcall_configs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trusted_contacts_id'), 'trusted_contacts', ['id'], unique=False)
    op.add_column('calls', sa.Column('is_trusted', sa.Boolean(), nullable=True))
    op.add_column('calls', sa.Column('is_spam', sa.Boolean(), nullable=True))
    op.add_column('calls', sa.Column('screening_action', sa.String(), nullable=True))
    op.add_column('calls', sa.Column('caller_name', sa.String(), nullable=True))
    op.add_column('calls', sa.Column('spam_score', sa.Integer(), nullable=True))
    op.add_column('calls', sa.Column('retell_call_id', sa.String(), nullable=True))
    op.add_column('calls', sa.Column('rootcall_transcript', sa.Text(), nullable=True))
    op.add_column('calls', sa.Column('scam_detected', sa.Boolean(), nullable=True))
    op.add_column('calls', sa.Column('scam_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('calls', 'scam_type')
    op.drop_column('calls', 'scam_detected')
    op.drop_column('calls', 'rootcall_transcript')
    op.drop_column('calls', 'retell_call_id')
    op.drop_column('calls', 'spam_score')
    op.drop_column('calls', 'caller_name')
    op.drop_column('calls', 'screening_action')
    op.drop_column('calls', 'is_spam')
    op.drop_column('calls', 'is_trusted')
    op.drop_index(op.f('ix_trusted_contacts_id'), table_name='trusted_contacts')
    op.drop_table('trusted_contacts')
    op.drop_index(op.f('ix_rootcall_configs_id'), table_name='rootcall_configs')
    op.drop_table('rootcall_configs')
    # ### end Alembic commands ###
