"""Add all VoIP models

Revision ID: 6eeff7f7e2f6
Revises: f6236c21f2cd
Create Date: 2025-10-17 16:49:14.111319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6eeff7f7e2f6'
down_revision: Union[str, None] = 'f6236c21f2cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
