"""add_retell_fields_to_ai_agent

Revision ID: 905754844f10
Revises: 7f82a86437f1
Create Date: 2025-10-23 17:07:35.729895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '905754844f10'
down_revision: Union[str, None] = '7f82a86437f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_agents', sa.Column('retell_agent_id', sa.String(), nullable=True))
    op.add_column('ai_agents', sa.Column('retell_llm_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_ai_agents_retell_agent_id'), 'ai_agents', ['retell_agent_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_agents_retell_agent_id'), table_name='ai_agents')
    op.drop_column('ai_agents', 'retell_llm_id')
    op.drop_column('ai_agents', 'retell_agent_id')
    # ### end Alembic commands ###
